name: CI
on:
  push:
    branches:
      - 0.6-maint
  pull_request:
    branches:
      - 0.6-maint
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1165

      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn', '**/deps.edn') }}

      - name: Clojure Version
        run: |
          clojure -version
          clojure -M -e '*clojure-version*'
      - name: Dependencies and Prep
        working-directory: service
        run: clojure -X:deps:local prep
      - name: Compile services
        working-directory: service
        run: clojure -T:build compile-java :aliases '[:local :servlet-api]'
      - name: Execute tests
        working-directory: tests
        run: clojure -X:test
      - name: Vulnerabilities Check
        working-directory: jetty
        run: clojure -J-Dclojure.main.report=stderr -J-Dorg.slf4j.simpleLogger.log.org.apache.commons=error -X:nvd :classpath \""$(clojure -Alocal -Spath)\""
